import { IconType } from "react-icons";
import {
	SiPython,
	SiJavascript,
	SiDocker,
	SiNextdotjs,
	SiReact,
	SiHtml5,
	SiCss3,
	SiSass,
	SiTailwindcss,
	SiPostgresql,
	SiMongodb,
	SiRedis,
	SiMysql,
	SiSupabase,
	SiDjango,
	SiFlask,
	SiFastapi,
	SiTypescript,
	SiGit,
	SiIbmcloud,
	SiVercel,
	SiAdobephotoshop,
	SiFigma,
	SiAnaconda,
	SiCloudflare,
	SiJupyter,
	SiNetlify,
	SiNodedotjs,
	SiPandas,
	SiPytorch,
	SiScikitlearn,
	SiTensorflow,
} from "react-icons/si";

const iconMap: Record<string, IconType> = {
	python: SiPython,
	javascript: SiJavascript,
	docker: SiDocker,
	nextjs: SiNextdotjs,
	reactjs: SiReact,
	nodejs: SiNodedotjs,
	htmlcss: SiHtml5,
	css: SiCss3,
	sass: SiSass,
	tailwindcss: SiTailwindcss,
	postgresql: SiPostgresql,
	mongodb: SiMongodb,
	redis: SiRedis,
	mysql: SiMysql,
	supabase: SiSupabase,
	django: SiDjango,
	flask: SiFlask,
	fastapi: SiFastapi,
	typescript: SiTypescript,
	git: SiGit,
	ibmcloud: SiIbmcloud,
	vercel: SiVercel,
	photoshop: SiAdobephotoshop,
	figma: SiFigma,
	anaconda: SiAnaconda,
	cloudflare: SiCloudflare,
	jupyter: SiJupyter,
	netlify: SiNetlify,
	pandas: SiPandas,
	pytorch: SiPytorch,
	scikitlearn: SiScikitlearn,
	tensorflow: SiTensorflow,
};

export function getIcon(skill: string) {
	const skillName = skill.replace(/[^\w]/g, "").toLowerCase();
	return iconMap[skillName] || null;
}
